### ISSUE TITLE
Tag for current Version

### ISSUE THREAD

**Issue by goldi42** [smichaelsen/typo3-dynamic-routing-pages#1]
Hello,
I want to ask, if it posible to set a tag for the current verison? So If the extension get an update for TYPO3 11 LTS it is still posible to install a version for TYPO3 10.
Thanks and Best Regards
Goldi42

**Comment by smichaelsen** [comment]
Thanks, I have just created 1.0.0.

The project I'm using this in will most likely be upgraded to v11 later this year. If anyone need it earlier, PRs are welcome :)
