### ISSUE TITLE
TYPO3 12 support

### ISSUE THREAD

**Issue by websi** [smichaelsen/typo3-dynamic-routing-pages#17]
Hi, i tested the branch `task/typo3v12` but that is not compatible with version 12.

```
Fatal error: Declaration of Smic\DynamicRoutingPages\Xclass\SiteConfiguration::write(string $siteIdentifier, array $configuration): void must be compatible with TYPO3\CMS\Core\Configuration\SiteConfiguration::write(string $siteIdentifier, array $configuration, bool $protectPlaceholders = false): void in /var/www/html/vendor/smic/dynamic-routing-pages/Classes/Xclass/SiteConfiguration.php on line 39
````

Is there any plans by you?

**Comment by websi** [comment]
I will provide a new MR with the new `SiteConfigurationLoadedEvent` from https://forge.typo3.org/issues/92778

**Comment by websi** [comment]
I removed the support for TYPO3 10. I hope these is not a problem.
Maybe we also remove the support for TYPO3 11 to remove the xclass.

**Comment by goldi42** [comment]
Hey,

How do we continue here?
Can the MR of @websi be merged?
TYPO3 12 support for the extension would be great.

Best regards
goldi42

**Comment by websi** [comment]
@smichaelsen Any update here?

**Comment by websi** [comment]
Is already done by #20.
