### ISSUE TITLE
Patch release?

### ISSUE THREAD

**Issue by Mabahe** [smichaelsen/typo3-dynamic-routing-pages#3]
Wow, guys, switching from a v10 compatible version to v11 should not get released as patch level version, please. Please respect Semantic Versioning. So it should be a version 2.0.0.

**Comment by smichaelsen** [comment]
You're right. That was a mistake. v10 compatiblity was meant to stay.

**Comment by smichaelsen** [comment]
Thanks for the report, we're releasing 1.0.2 today with restored compatibility for TYPO3 v10.

**Comment by Mabahe** [comment]
thx 👍
